import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from "next/font/google";
import enUS from "antd/es/locale/en_US";

import "./globals.css";
import { App, ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider locale={enUS}>
          <AntdRegistry>
            <App>{children}</App>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
};

export default RootLayout;
